sudo: false
language: node_js
node_js: stable
env:
  global:
  - DISPLAY=:99.0
cache:
  directories:
  - node_modules
before_install:
- export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=linux64&lang=en-US'
- wget -O /tmp/firefox-aurora-latest.tar.bz2 $FIREFOX_SOURCE_URL
- tar -xjf /tmp/firefox-aurora-latest.tar.bz2
- export JPM_FIREFOX_BINARY=$PWD/firefox/firefox
- sh -e /etc/init.d/xvfb start
script:
- npm run lint
- npm run build
- npm test
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/tabscroll@mthamil-*.xpi"
  skip_cleanup: true
  on:
    tags: true
