sudo: false
language: node_js
node_js: stable
addons:
  firefox: "47.0"
env:
  global:
  - DISPLAY=:99.0
  - JPM_FIREFOX_BINARY=/usr/local/bin/firefox
cache:
  directories:
  - node_modules
before_install:
- sh -e /etc/init.d/xvfb start
script:
- npm run lint
- npm run build
- npm test
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/tabscroll@mthamil-*.xpi"
  skip_cleanup: true
  on:
    tags: true
